# loops over all elements in list and prints them
function(print_list)
    foreach(item IN LISTS ${ARGN})
        print(${item})
    endforeach(item IN LISTS)
endfunction()

# prints the value of a variable and check if its an environment variable
function(print)
    foreach(var ${ARGN})
        if(DEFINED ENV{${var}})
            message("┣━ ENV: ${var} = $ENV{${var}}")
        elseif(DEFINED ${var})
            message("┣━ ${var} = ${${var}}")
        else()
            message("┣━ ${var}")
        endif()
    endforeach()
endfunction(print)

# loops over all arguments and prints the result in a nice way
function(print_block message)
   print_block_start()
    message("┣━ ${ARGV0}")
    if(${ARGC} GREATER 1)
        message("┣━━━━━━━━━━━━━━━━━━━━━")
    endif()
    foreach(arg ${ARGN})
        if(${arg} MATCHES ";")
            print_list(${arg})
        else()
            print(${arg})
    endif()
    endforeach()
    print_block_end()
endfunction(print_block)

function(print_block_start)
    message("┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓")
endfunction(print_block_start)

function(print_block_end)
    message("┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛")
endfunction(print_block_end)
